[package]
name = "solar_cli"
version = "0.1.0"
edition = "2024"
license = "Unlicense"
description = "Command-line interface for the Solar Travel Calculator"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
solar_travel_calculator = { path = "../.." }
