[package]
name = "solar_config"
version = "0.1.0"
edition = "2024"
license = "Unlicense"
description = "Configuration parsing and validation for the Solar Travel Calculator"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "2.0"
toml = "0.8"
