name = "CALLISTO"
spice_name = "CALLISTO"
parent_spice = "JUPITER BARYCENTER"
mu_km3_s2 = 7179.289
radius_km = 2410.3
soi_radius_km = 116000.0
default_parking_altitude_km = 100.0
surface_gravity_m_s2 = 1.235
mass_kg = 1.0759e+23

[atmosphere]
exists = false
scale_height_km = 0.0
surface_density_kg_m3 = 0.0
