name = "CERES"
spice_name = "CERES"
mu_km3_s2 = 62.63
radius_km = 473.0
soi_radius_km = 160000.0
default_parking_altitude_km = 50.0
surface_gravity_m_s2 = 0.27
mass_kg = 9.393e+20

[atmosphere]
exists = false
scale_height_km = 0.0
surface_density_kg_m3 = 0.0
