name = "CHARON"
spice_name = "CHARON"
parent_spice = "PLUTO BARYCENTER"
mu_km3_s2 = 102.8
radius_km = 606.0
soi_radius_km = 20000.0
default_parking_altitude_km = 60.0
surface_gravity_m_s2 = 0.288
mass_kg = 1.586e+21

[atmosphere]
exists = false
scale_height_km = 0.0
surface_density_kg_m3 = 0.0
