name = "ERIS"
spice_name = "ERIS"
mu_km3_s2 = 1108.0
radius_km = 1163.0
soi_radius_km = 37000.0
default_parking_altitude_km = 60.0
surface_gravity_m_s2 = 0.82
mass_kg = 1.66e+22

[atmosphere]
exists = false
scale_height_km = 0.0
surface_density_kg_m3 = 0.0
