name = "EUROPA"
spice_name = "EUROPA"
parent_spice = "JUPITER BARYCENTER"
mu_km3_s2 = 3202.739
radius_km = 1560.8
soi_radius_km = 67100.0
default_parking_altitude_km = 75.0
surface_gravity_m_s2 = 1.314
mass_kg = 4.8e+22

[atmosphere]
exists = false
scale_height_km = 0.0
surface_density_kg_m3 = 0.0
