name = "GANYMEDE"
spice_name = "GANYMEDE"
parent_spice = "JUPITER BARYCENTER"
mu_km3_s2 = 9887.8
radius_km = 2634.1
soi_radius_km = 107000.0
default_parking_altitude_km = 100.0
surface_gravity_m_s2 = 1.428
mass_kg = 1.4819e+23

[atmosphere]
exists = false
scale_height_km = 0.0
surface_density_kg_m3 = 0.0
