name = "URANUS"
spice_name = "URANUS BARYCENTER"
mu_km3_s2 = 5793951.0
radius_km = 25362.0
soi_radius_km = 5180000.0
default_parking_altitude_km = 900.0
surface_gravity_m_s2 = 8.69
mass_kg = 8.681e+25

[atmosphere]
exists = true
scale_height_km = 27.0
surface_density_kg_m3 = 0.42
