name = "VENUS"
spice_name = "VENUS BARYCENTER"
mu_km3_s2 = 324858.633
radius_km = 6051.8
soi_radius_km = 616000.0
default_parking_altitude_km = 250.0
surface_gravity_m_s2 = 8.87
mass_kg = 4.8675e+24

[atmosphere]
exists = true
scale_height_km = 15.9
surface_density_kg_m3 = 65.0
