name = "VESTA"
spice_name = "VESTA"
mu_km3_s2 = 17.8
radius_km = 262.7
soi_radius_km = 80000.0
default_parking_altitude_km = 30.0
surface_gravity_m_s2 = 0.25
mass_kg = 2.5908e+20

[atmosphere]
exists = false
scale_height_km = 0.0
surface_density_kg_m3 = 0.0
